import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StreamingProvider } from "@/components/providers/streaming-provider";
import { Toaster } from "sonner";
import { cn } from "@/lib/utils";
import { Footer } from "@/components/footer";
import { Webcam } from "@/components/webcam";
import { Sidebar } from "@/components/sidebar";
import { PlayerController } from "@/components/player-controller";
import { MiroBoard } from "@/components/boards/miro-board";
import { JoyStickControllerProvider } from "@/components/providers/player-controller-provider";
import { Layout as SceneLayout } from "@/components/dom/layout";
import { TextChannel } from "@/components/text-channel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "fixed h-full w-full bg-blue-gray-50")}
      >
        <JoyStickControllerProvider>
          <StreamingProvider>
            <Toaster />
            <Footer />
            <Webcam />
            <Sidebar />
            <PlayerController />
            <MiroBoard />
            <TextChannel />
            <SceneLayout>{children}</SceneLayout>
          </StreamingProvider>
        </JoyStickControllerProvider>
      </body>
    </html>
  );
}
